name: Haskell CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc: ["8.8.1", "8.5.6"]
        cabal: ["3.0"]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Install dependencies
      run: |
        cabal update
    - name: Build
      run: |
        cabal new-build
