name: HLint CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: hlint
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc: ["8.8.1"]
        cabal: ["3.0"]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Install hlint
      run: |
        cabal update
        cabal new-install hlint --installdir=/usr/bin/
    - name: Run hlint
      run: |
        hlint -g
